/*
 * This file is generated by jOOQ.
 */
package com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.records;


import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.Character;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterRecord extends UpdatableRecordImpl<CharacterRecord> implements Record17<Integer, String, String, String, String, String, String, String, Integer, Integer, Integer, String, byte[], byte[], byte[], byte[], byte[]> {

    private static final long serialVersionUID = -1173963095;

    /**
     * Setter for <code>nyrheim.character.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nyrheim.character.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nyrheim.character.player_uuid</code>.
     */
    public void setPlayerUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nyrheim.character.player_uuid</code>.
     */
    public String getPlayerUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nyrheim.character.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nyrheim.character.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nyrheim.character.family_name</code>.
     */
    public void setFamilyName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nyrheim.character.family_name</code>.
     */
    public String getFamilyName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nyrheim.character.height</code>.
     */
    public void setHeight(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nyrheim.character.height</code>.
     */
    public String getHeight() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nyrheim.character.weight</code>.
     */
    public void setWeight(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>nyrheim.character.weight</code>.
     */
    public String getWeight() {
        return (String) get(5);
    }

    /**
     * Setter for <code>nyrheim.character.appearance</code>.
     */
    public void setAppearance(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>nyrheim.character.appearance</code>.
     */
    public String getAppearance() {
        return (String) get(6);
    }

    /**
     * Setter for <code>nyrheim.character.presence</code>.
     */
    public void setPresence(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>nyrheim.character.presence</code>.
     */
    public String getPresence() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nyrheim.character.age</code>.
     */
    public void setAge(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>nyrheim.character.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>nyrheim.character.experience</code>.
     */
    public void setExperience(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>nyrheim.character.experience</code>.
     */
    public Integer getExperience() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>nyrheim.character.exhaustion</code>.
     */
    public void setExhaustion(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>nyrheim.character.exhaustion</code>.
     */
    public Integer getExhaustion() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>nyrheim.character.race</code>.
     */
    public void setRace(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>nyrheim.character.race</code>.
     */
    public String getRace() {
        return (String) get(11);
    }

    /**
     * Setter for <code>nyrheim.character.helmet</code>.
     */
    public void setHelmet(byte[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>nyrheim.character.helmet</code>.
     */
    public byte[] getHelmet() {
        return (byte[]) get(12);
    }

    /**
     * Setter for <code>nyrheim.character.chestplate</code>.
     */
    public void setChestplate(byte[] value) {
        set(13, value);
    }

    /**
     * Getter for <code>nyrheim.character.chestplate</code>.
     */
    public byte[] getChestplate() {
        return (byte[]) get(13);
    }

    /**
     * Setter for <code>nyrheim.character.leggings</code>.
     */
    public void setLeggings(byte[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>nyrheim.character.leggings</code>.
     */
    public byte[] getLeggings() {
        return (byte[]) get(14);
    }

    /**
     * Setter for <code>nyrheim.character.boots</code>.
     */
    public void setBoots(byte[] value) {
        set(15, value);
    }

    /**
     * Getter for <code>nyrheim.character.boots</code>.
     */
    public byte[] getBoots() {
        return (byte[]) get(15);
    }

    /**
     * Setter for <code>nyrheim.character.inventory_contents</code>.
     */
    public void setInventoryContents(byte[] value) {
        set(16, value);
    }

    /**
     * Getter for <code>nyrheim.character.inventory_contents</code>.
     */
    public byte[] getInventoryContents() {
        return (byte[]) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, Integer, Integer, Integer, String, byte[], byte[], byte[], byte[], byte[]> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, String, String, String, String, String, String, String, Integer, Integer, Integer, String, byte[], byte[], byte[], byte[], byte[]> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Character.CHARACTER.ID;
    }

    @Override
    public Field<String> field2() {
        return Character.CHARACTER.PLAYER_UUID;
    }

    @Override
    public Field<String> field3() {
        return Character.CHARACTER.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Character.CHARACTER.FAMILY_NAME;
    }

    @Override
    public Field<String> field5() {
        return Character.CHARACTER.HEIGHT;
    }

    @Override
    public Field<String> field6() {
        return Character.CHARACTER.WEIGHT;
    }

    @Override
    public Field<String> field7() {
        return Character.CHARACTER.APPEARANCE;
    }

    @Override
    public Field<String> field8() {
        return Character.CHARACTER.PRESENCE;
    }

    @Override
    public Field<Integer> field9() {
        return Character.CHARACTER.AGE;
    }

    @Override
    public Field<Integer> field10() {
        return Character.CHARACTER.EXPERIENCE;
    }

    @Override
    public Field<Integer> field11() {
        return Character.CHARACTER.EXHAUSTION;
    }

    @Override
    public Field<String> field12() {
        return Character.CHARACTER.RACE;
    }

    @Override
    public Field<byte[]> field13() {
        return Character.CHARACTER.HELMET;
    }

    @Override
    public Field<byte[]> field14() {
        return Character.CHARACTER.CHESTPLATE;
    }

    @Override
    public Field<byte[]> field15() {
        return Character.CHARACTER.LEGGINGS;
    }

    @Override
    public Field<byte[]> field16() {
        return Character.CHARACTER.BOOTS;
    }

    @Override
    public Field<byte[]> field17() {
        return Character.CHARACTER.INVENTORY_CONTENTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlayerUuid();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getFamilyName();
    }

    @Override
    public String component5() {
        return getHeight();
    }

    @Override
    public String component6() {
        return getWeight();
    }

    @Override
    public String component7() {
        return getAppearance();
    }

    @Override
    public String component8() {
        return getPresence();
    }

    @Override
    public Integer component9() {
        return getAge();
    }

    @Override
    public Integer component10() {
        return getExperience();
    }

    @Override
    public Integer component11() {
        return getExhaustion();
    }

    @Override
    public String component12() {
        return getRace();
    }

    @Override
    public byte[] component13() {
        return getHelmet();
    }

    @Override
    public byte[] component14() {
        return getChestplate();
    }

    @Override
    public byte[] component15() {
        return getLeggings();
    }

    @Override
    public byte[] component16() {
        return getBoots();
    }

    @Override
    public byte[] component17() {
        return getInventoryContents();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlayerUuid();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getFamilyName();
    }

    @Override
    public String value5() {
        return getHeight();
    }

    @Override
    public String value6() {
        return getWeight();
    }

    @Override
    public String value7() {
        return getAppearance();
    }

    @Override
    public String value8() {
        return getPresence();
    }

    @Override
    public Integer value9() {
        return getAge();
    }

    @Override
    public Integer value10() {
        return getExperience();
    }

    @Override
    public Integer value11() {
        return getExhaustion();
    }

    @Override
    public String value12() {
        return getRace();
    }

    @Override
    public byte[] value13() {
        return getHelmet();
    }

    @Override
    public byte[] value14() {
        return getChestplate();
    }

    @Override
    public byte[] value15() {
        return getLeggings();
    }

    @Override
    public byte[] value16() {
        return getBoots();
    }

    @Override
    public byte[] value17() {
        return getInventoryContents();
    }

    @Override
    public CharacterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CharacterRecord value2(String value) {
        setPlayerUuid(value);
        return this;
    }

    @Override
    public CharacterRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CharacterRecord value4(String value) {
        setFamilyName(value);
        return this;
    }

    @Override
    public CharacterRecord value5(String value) {
        setHeight(value);
        return this;
    }

    @Override
    public CharacterRecord value6(String value) {
        setWeight(value);
        return this;
    }

    @Override
    public CharacterRecord value7(String value) {
        setAppearance(value);
        return this;
    }

    @Override
    public CharacterRecord value8(String value) {
        setPresence(value);
        return this;
    }

    @Override
    public CharacterRecord value9(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public CharacterRecord value10(Integer value) {
        setExperience(value);
        return this;
    }

    @Override
    public CharacterRecord value11(Integer value) {
        setExhaustion(value);
        return this;
    }

    @Override
    public CharacterRecord value12(String value) {
        setRace(value);
        return this;
    }

    @Override
    public CharacterRecord value13(byte[] value) {
        setHelmet(value);
        return this;
    }

    @Override
    public CharacterRecord value14(byte[] value) {
        setChestplate(value);
        return this;
    }

    @Override
    public CharacterRecord value15(byte[] value) {
        setLeggings(value);
        return this;
    }

    @Override
    public CharacterRecord value16(byte[] value) {
        setBoots(value);
        return this;
    }

    @Override
    public CharacterRecord value17(byte[] value) {
        setInventoryContents(value);
        return this;
    }

    @Override
    public CharacterRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Integer value10, Integer value11, String value12, byte[] value13, byte[] value14, byte[] value15, byte[] value16, byte[] value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterRecord
     */
    public CharacterRecord() {
        super(Character.CHARACTER);
    }

    /**
     * Create a detached, initialised CharacterRecord
     */
    public CharacterRecord(Integer id, String playerUuid, String firstName, String familyName, String height, String weight, String appearance, String presence, Integer age, Integer experience, Integer exhaustion, String race, byte[] helmet, byte[] chestplate, byte[] leggings, byte[] boots, byte[] inventoryContents) {
        super(Character.CHARACTER);

        set(0, id);
        set(1, playerUuid);
        set(2, firstName);
        set(3, familyName);
        set(4, height);
        set(5, weight);
        set(6, appearance);
        set(7, presence);
        set(8, age);
        set(9, experience);
        set(10, exhaustion);
        set(11, race);
        set(12, helmet);
        set(13, chestplate);
        set(14, leggings);
        set(15, boots);
        set(16, inventoryContents);
    }
}
