name: PenAndPaper
version: @version@
authors:
- LiamVI
- alyphen
main: net.nyrheim.penandpaper.PenAndPaper
api-version: 1.14
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-skill-lib-bukkit
- rpk-class-lib-bukkit
- rpk-experience-lib-bukkit
- rpk-stat-lib-bukkit
- rpk-language-lib-bukkit
commands:
  character:
    description: |
      Character management commands
      /char - Displays your character card
      /char [player] - Displays the character card of the specified player
      /char stats - Displays your stats
      /char set name [name] - Sets your name
      /char set age [age] - Sets your age
      /char set height [height] - Sets your height
      /char set weight [weight] - Sets your weight
      /char set appearance [appearance] - Sets your appearance
      /char set presence [presence] - Sets your presence
      /char add appearance [appearance] - Appends information to your appearance
      /char add presence [presence] - Appends information to your presence
      /char delete [id] - Deletes a character
    usage: /<command>
    aliases:
    - char
  experience:
    description: |
      Experience management commands
      /exp add [player] [experience] - Gives the player's active character the given amount of experience
      /exp set [player] [experience] - Sets the player's active character's experience to the given value
      /exp - Shows your experience
    usage: /<command>
    aliases:
    - exp
  soul:
    description: Soul management command
    usage: /<command>
  levelup:
    description: Levels up a class
    usage: /<command>
  ability:
    description: |
      Ability management commands
      /ability set [player] [ability] [score] - Sets the player's active character's ability score
      /ability choice - Views your ability choices
    usage: /<command>
  class:
    description: |
      Class management commands
      /class approve [player] [class] - Approves a player's attempt to multiclass into the given class
    usage: /<command>
  item:
    description: Gives you an item
    usage: /<command> [type] (amount)
    aliases:
    - i
  hp:
    description: Shows your current and maximum hit points
    usage: /<command>
  dhp:
    description: Takes damage to your hit points
    usage: /<command> [damage]
  ihp:
    description: Heals yourself for the specified amount
    usage: /<command> [health]
    aliases:
    - ahp
  sethp:
    description: Sets your HP
    usage: /<command> [health]
  exhaustion:
    description: |
      Exhaustion management command
      /exhaustion add [player] [amount] - Adds an amount of exhaustion to a player
      /exhaustion remove [player] [amount] - Removes an amount of exhaustion from a player
      /exhaustion set [player] [amount] - Sets a player's exhaustion
    usage: /<command> [add|remove|set]
    aliases:
    - exh
  roll:
    description: Rolls the number of die specified
    usage: /<command> [XdN+Y]
  temphp:
    description: Displays your temp HP
    usage: /<command>
    aliases:
    - thp
  password:
    description: Sets your password for login to web apps etc
    usage: /<command>
permissions:
  penandpaper.command.exp.add:
    description: Allows adding experience to characters
    default: op
  penandpaper.command.exp.set:
    description: Allows setting experience for characters
    default: op
  penandpaper.command.exp:
    description: Allows viewing your experience
    default: op
  penandpaper.command.exp.other:
    description: Allows viewing other players'' characters'' experience
    default: op
  penandpaper.command.character.set.name.other:
    description: Allows setting the name of other players'' characters
    default: op
  penandpaper.command.character.set.age.other:
    description: Allows setting the age of other players'' characters
    default: op
  penandpaper.command.character.set.height.other:
    description: Allows setting the height of other players'' characters
    default: op
  penandpaper.command.character.set.weight.other:
    description: Allows setting the weight of other players'' characters
    default: op
  penandpaper.command.character.set.appearance.other:
    description: Allows setting the appearance of other players'' characters
    default: op
  penandpaper.command.character.set.presence.other:
    description: Allows setting the presence of other players'' characters
    default: op
  penandpaper.command.character.set.race.other:
    description: Allows setting the race of other players'' characters
    default: op
  penandpaper.command.character.add.appearance.other:
    description: Allows extending the appearance of other players'' characters
    default: op
  penandpaper.command.character.add.presence.other:
    description: Allows extending the presence of other players'' characters
    default: op
  penandpaper.command.ability.set:
    description: Allows setting ability scores
    default: op
  penandpaper.multiclassapproval:
    description: Allows viewing multiclass approval notifications
    default: op
  penandpaper.command.class.approve:
    description: Allows approving multiclass combinations
    default: op
  penandpaper.command.character.stats.other:
    description: Allows viewing stats of other players'' characters
    default: op
  penandpaper.command.item:
    description: Allows giving yourself items
    default: op
  penandpaper.command.dhp.other:
    description: Allows decreasing other player''s HP
    default: op
  penandpaper.command.ihp.other:
    description: Allows increasing other player''s HP
    default: op
  penandpaper.command.sethp.other:
    description: Allows setting other player''s HP
    default: op
  penandpaper.command.hp.other:
    description: Allows viewing other players'' HP
    default: op
  penandpaper.command.exhaustion.add:
    description: Allows you to add exhaustion to players
    default: op
  penandpaper.command.exhaustion.remove:
    description: Allows you to remove exhaustion from players
    default: op
  penandpaper.command.exhaustion.set:
    description: Allows you to set exhaustion for players
    default: op
  penandpaper.warlock:
    description: Allows you to select the Warlock class
    default: op
  penandpaper.2slot:
    description: Allows you to use a second character slot
    default: op
  penandpaper.3slot:
    description: Allows you to use a third character slot
    default: op
  penandpaper.copper:
    description: Allows all Copper donator functionality.
    default: op
  penandpaper.silver:
    description: Allows all Silver donator functionality.
  penandpaper.gold:
    description: Allows all Gold donator functionality.
    default: op
  penandpaper.platinum:
    description: Allows all Platinum donator functionality.
    default: op
  penandpaper.dungeonmaster:
    description: Allows all dungeon master functionality
    default: op
  penandpaper.gamemaster:
    description: Allows all game master functionality.
    default: op
  penandpaper.admin:
    description: Allows all admin functionality
    default: op
    children:
    - penandpaper.command.exp.add
    - penandpaper.command.exp.set
    - penandpaper.command.exp
    - penandpaper.command.exp.other
    - penandpaper.command.character.set.name.other
    - penandpaper.command.character.set.age.other
    - penandpaper.command.character.set.height.other
    - penandpaper.command.character.set.weight.other
    - penandpaper.command.character.set.appearance.other
    - penandpaper.command.character.set.presence.other
    - penandpaper.command.character.add.appearance.other
    - penandpaper.command.character.add.presence.other
    - penandpaper.command.character.set.race.other
    - penandpaper.command.ability.set
    - penandpaper.multiclassapproval
    - penandpaper.command.class.approve
    - penandpaper.command.character.stats.other
    - penandpaper.command.item
    - penandpaper.command.dhp.other
    - penandpaper.command.ihp.other
    - penandpaper.command.sethp.other
    - penandpaper.command.hp.other
    - penandpaper.command.exhaustion.add
    - penandpaper.command.exhaustion.remove
    - penandpaper.command.exhaustion.set
