name: PenandPaper
version: @version@
author: LiamVI
main: com.github.liamvii.penandpaper.Pen
api-version: 1.13
commands:
  character:
    description: |
      Character management commands
      /char - Displays your character card
      /char [player] - Displays the character card of the specified player
      /char stats - Displays your stats
      /char set age [age] - Sets your age
      /char set height [height] - Sets your height
      /char set weight [weight] - Sets your weight
      /char set appearance [appearance] - Sets your appearance
      /char set presence [presence] - Sets your presence
      /char set exp [player] [exp] - Sets a player''s active character''s experience
    usage: /<command>
    aliases:
    - char
  soul:
    description: Character-related commands.
    usage: /soul
  exp:
    description: exp commands
    usage: /exp
permissions:
  penandpaper.command.character.set.exp:
    description: Allows setting experience for characters
    default: op
  penandpaper.admin:
    description: Allows all admin functionality
    default: op
    children:
    - penandpaper.command.character.set.exp