name: PenandPaper
version: @version@
author: LiamVI
main: com.github.liamvii.penandpaper.Pen
api-version: 1.13
commands:
  soul:
    description: Character-related commands.
    usage: /soul
  exp:
    description: exp commands
    usage: /exp