/*
 * This file is generated by jOOQ.
 */
package com.github.liamvii.penandpaper.database.jooq.tables;


import com.github.liamvii.penandpaper.database.jooq.Keys;
import com.github.liamvii.penandpaper.database.jooq.Nyrheim;
import com.github.liamvii.penandpaper.database.jooq.tables.records.CharacterAbilityScoreChoiceRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterAbilityScoreChoice extends TableImpl<CharacterAbilityScoreChoiceRecord> {

    private static final long serialVersionUID = 1444574173;

    /**
     * The reference instance of <code>nyrheim.character_ability_score_choice</code>
     */
    public static final CharacterAbilityScoreChoice CHARACTER_ABILITY_SCORE_CHOICE = new CharacterAbilityScoreChoice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterAbilityScoreChoiceRecord> getRecordType() {
        return CharacterAbilityScoreChoiceRecord.class;
    }

    /**
     * The column <code>nyrheim.character_ability_score_choice.character_id</code>.
     */
    public final TableField<CharacterAbilityScoreChoiceRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_ability_score_choice.ability</code>.
     */
    public final TableField<CharacterAbilityScoreChoiceRecord, String> ABILITY = createField(DSL.name("ability"), org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_ability_score_choice.score</code>.
     */
    public final TableField<CharacterAbilityScoreChoiceRecord, Integer> SCORE = createField(DSL.name("score"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>nyrheim.character_ability_score_choice</code> table reference
     */
    public CharacterAbilityScoreChoice() {
        this(DSL.name("character_ability_score_choice"), null);
    }

    /**
     * Create an aliased <code>nyrheim.character_ability_score_choice</code> table reference
     */
    public CharacterAbilityScoreChoice(String alias) {
        this(DSL.name(alias), CHARACTER_ABILITY_SCORE_CHOICE);
    }

    /**
     * Create an aliased <code>nyrheim.character_ability_score_choice</code> table reference
     */
    public CharacterAbilityScoreChoice(Name alias) {
        this(alias, CHARACTER_ABILITY_SCORE_CHOICE);
    }

    private CharacterAbilityScoreChoice(Name alias, Table<CharacterAbilityScoreChoiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterAbilityScoreChoice(Name alias, Table<CharacterAbilityScoreChoiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CharacterAbilityScoreChoice(Table<O> child, ForeignKey<O, CharacterAbilityScoreChoiceRecord> key) {
        super(child, key, CHARACTER_ABILITY_SCORE_CHOICE);
    }

    @Override
    public Schema getSchema() {
        return Nyrheim.NYRHEIM;
    }

    @Override
    public UniqueKey<CharacterAbilityScoreChoiceRecord> getPrimaryKey() {
        return Keys.KEY_CHARACTER_ABILITY_SCORE_CHOICE_PRIMARY;
    }

    @Override
    public List<UniqueKey<CharacterAbilityScoreChoiceRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterAbilityScoreChoiceRecord>>asList(Keys.KEY_CHARACTER_ABILITY_SCORE_CHOICE_PRIMARY);
    }

    @Override
    public List<ForeignKey<CharacterAbilityScoreChoiceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterAbilityScoreChoiceRecord, ?>>asList(Keys.CHARACTER_ABILITY_CHOICE_CHARACTER_ID_FK);
    }

    public Character character() {
        return new Character(this, Keys.CHARACTER_ABILITY_CHOICE_CHARACTER_ID_FK);
    }

    @Override
    public CharacterAbilityScoreChoice as(String alias) {
        return new CharacterAbilityScoreChoice(DSL.name(alias), this);
    }

    @Override
    public CharacterAbilityScoreChoice as(Name alias) {
        return new CharacterAbilityScoreChoice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterAbilityScoreChoice rename(String name) {
        return new CharacterAbilityScoreChoice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterAbilityScoreChoice rename(Name name) {
        return new CharacterAbilityScoreChoice(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
