/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.penandpaper.database.jooq.tables;


import java.util.Arrays;
import java.util.List;

import net.nyrheim.penandpaper.database.jooq.Keys;
import net.nyrheim.penandpaper.database.jooq.Nyrheim;
import net.nyrheim.penandpaper.database.jooq.tables.records.CharacterTempAbilityScoreRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterTempAbilityScore extends TableImpl<CharacterTempAbilityScoreRecord> {

    private static final long serialVersionUID = -1374569071;

    /**
     * The reference instance of <code>nyrheim.character_temp_ability_score</code>
     */
    public static final CharacterTempAbilityScore CHARACTER_TEMP_ABILITY_SCORE = new CharacterTempAbilityScore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterTempAbilityScoreRecord> getRecordType() {
        return CharacterTempAbilityScoreRecord.class;
    }

    /**
     * The column <code>nyrheim.character_temp_ability_score.character_id</code>.
     */
    public final TableField<CharacterTempAbilityScoreRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_temp_ability_score.ability</code>.
     */
    public final TableField<CharacterTempAbilityScoreRecord, String> ABILITY = createField(DSL.name("ability"), org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>nyrheim.character_temp_ability_score.score</code>.
     */
    public final TableField<CharacterTempAbilityScoreRecord, Integer> SCORE = createField(DSL.name("score"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>nyrheim.character_temp_ability_score</code> table reference
     */
    public CharacterTempAbilityScore() {
        this(DSL.name("character_temp_ability_score"), null);
    }

    /**
     * Create an aliased <code>nyrheim.character_temp_ability_score</code> table reference
     */
    public CharacterTempAbilityScore(String alias) {
        this(DSL.name(alias), CHARACTER_TEMP_ABILITY_SCORE);
    }

    /**
     * Create an aliased <code>nyrheim.character_temp_ability_score</code> table reference
     */
    public CharacterTempAbilityScore(Name alias) {
        this(alias, CHARACTER_TEMP_ABILITY_SCORE);
    }

    private CharacterTempAbilityScore(Name alias, Table<CharacterTempAbilityScoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterTempAbilityScore(Name alias, Table<CharacterTempAbilityScoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CharacterTempAbilityScore(Table<O> child, ForeignKey<O, CharacterTempAbilityScoreRecord> key) {
        super(child, key, CHARACTER_TEMP_ABILITY_SCORE);
    }

    @Override
    public Schema getSchema() {
        return Nyrheim.NYRHEIM;
    }

    @Override
    public UniqueKey<CharacterTempAbilityScoreRecord> getPrimaryKey() {
        return Keys.KEY_CHARACTER_TEMP_ABILITY_SCORE_PRIMARY;
    }

    @Override
    public List<UniqueKey<CharacterTempAbilityScoreRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterTempAbilityScoreRecord>>asList(Keys.KEY_CHARACTER_TEMP_ABILITY_SCORE_PRIMARY);
    }

    @Override
    public List<ForeignKey<CharacterTempAbilityScoreRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterTempAbilityScoreRecord, ?>>asList(Keys.CHARACTER_TEMP_ABILITY_SCORE_CHARACTER_ID_FK);
    }

    public Character character() {
        return new Character(this, Keys.CHARACTER_TEMP_ABILITY_SCORE_CHARACTER_ID_FK);
    }

    @Override
    public CharacterTempAbilityScore as(String alias) {
        return new CharacterTempAbilityScore(DSL.name(alias), this);
    }

    @Override
    public CharacterTempAbilityScore as(Name alias) {
        return new CharacterTempAbilityScore(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterTempAbilityScore rename(String name) {
        return new CharacterTempAbilityScore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterTempAbilityScore rename(Name name) {
        return new CharacterTempAbilityScore(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
