/*
 * This file is generated by jOOQ.
 */
package com.github.liamvii.penandpaper.database.jooq.nyrheim;


import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.ActiveCharacter;
import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.Character;
import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.CharacterAbilityScore;
import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.CharacterClass;
import com.github.liamvii.penandpaper.database.jooq.nyrheim.tables.CharacterTempAbilityScore;


/**
 * Convenience access to all tables in nyrheim
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nyrheim.active_character</code>.
     */
    public static final ActiveCharacter ACTIVE_CHARACTER = ActiveCharacter.ACTIVE_CHARACTER;

    /**
     * The table <code>nyrheim.character</code>.
     */
    public static final Character CHARACTER = Character.CHARACTER;

    /**
     * The table <code>nyrheim.character_ability_score</code>.
     */
    public static final CharacterAbilityScore CHARACTER_ABILITY_SCORE = CharacterAbilityScore.CHARACTER_ABILITY_SCORE;

    /**
     * The table <code>nyrheim.character_class</code>.
     */
    public static final CharacterClass CHARACTER_CLASS = CharacterClass.CHARACTER_CLASS;

    /**
     * The table <code>nyrheim.character_temp_ability_score</code>.
     */
    public static final CharacterTempAbilityScore CHARACTER_TEMP_ABILITY_SCORE = CharacterTempAbilityScore.CHARACTER_TEMP_ABILITY_SCORE;
}
