/*
 * This file is generated by jOOQ.
 */
package com.github.liamvii.penandpaper.database.jooq.tables.records;


import com.github.liamvii.penandpaper.database.jooq.tables.CharacterClass;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterClassRecord extends UpdatableRecordImpl<CharacterClassRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1899926729;

    /**
     * Setter for <code>nyrheim.character_class.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nyrheim.character_class.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nyrheim.character_class.class_name</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nyrheim.character_class.class_name</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nyrheim.character_class.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>nyrheim.character_class.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CharacterClass.CHARACTER_CLASS.CHARACTER_ID;
    }

    @Override
    public Field<String> field2() {
        return CharacterClass.CHARACTER_CLASS.CLASS_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return CharacterClass.CHARACTER_CLASS.LEVEL;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public String component2() {
        return getClassName();
    }

    @Override
    public Integer component3() {
        return getLevel();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public String value2() {
        return getClassName();
    }

    @Override
    public Integer value3() {
        return getLevel();
    }

    @Override
    public CharacterClassRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public CharacterClassRecord value2(String value) {
        setClassName(value);
        return this;
    }

    @Override
    public CharacterClassRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public CharacterClassRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterClassRecord
     */
    public CharacterClassRecord() {
        super(CharacterClass.CHARACTER_CLASS);
    }

    /**
     * Create a detached, initialised CharacterClassRecord
     */
    public CharacterClassRecord(Integer characterId, String className, Integer level) {
        super(CharacterClass.CHARACTER_CLASS);

        set(0, characterId);
        set(1, className);
        set(2, level);
    }
}
