/*
 * This file is generated by jOOQ.
 */
package net.nyrheim.penandpaper.database.jooq;


import net.nyrheim.penandpaper.database.jooq.tables.ActiveCharacter;
import net.nyrheim.penandpaper.database.jooq.tables.Character;
import net.nyrheim.penandpaper.database.jooq.tables.CharacterAbilityScore;
import net.nyrheim.penandpaper.database.jooq.tables.CharacterAbilityScoreChoice;
import net.nyrheim.penandpaper.database.jooq.tables.CharacterClass;
import net.nyrheim.penandpaper.database.jooq.tables.CharacterTempAbilityScore;
import net.nyrheim.penandpaper.database.jooq.tables.Player;


/**
 * Convenience access to all tables in nyrheim
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nyrheim.active_character</code>.
     */
    public static final ActiveCharacter ACTIVE_CHARACTER = ActiveCharacter.ACTIVE_CHARACTER;

    /**
     * The table <code>nyrheim.character</code>.
     */
    public static final Character CHARACTER = Character.CHARACTER;

    /**
     * The table <code>nyrheim.character_ability_score</code>.
     */
    public static final CharacterAbilityScore CHARACTER_ABILITY_SCORE = CharacterAbilityScore.CHARACTER_ABILITY_SCORE;

    /**
     * The table <code>nyrheim.character_ability_score_choice</code>.
     */
    public static final CharacterAbilityScoreChoice CHARACTER_ABILITY_SCORE_CHOICE = CharacterAbilityScoreChoice.CHARACTER_ABILITY_SCORE_CHOICE;

    /**
     * The table <code>nyrheim.character_class</code>.
     */
    public static final CharacterClass CHARACTER_CLASS = CharacterClass.CHARACTER_CLASS;

    /**
     * The table <code>nyrheim.character_temp_ability_score</code>.
     */
    public static final CharacterTempAbilityScore CHARACTER_TEMP_ABILITY_SCORE = CharacterTempAbilityScore.CHARACTER_TEMP_ABILITY_SCORE;

    /**
     * The table <code>nyrheim.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
