Database Username: Liam # The username you intend to access the db through.
Database Password: J53da25fs # The password.
Database Path: jdbc:mysql://localhost:3306/penandpaper # Your database URL. This is CASE SENSITIVE.
# You /must/ format the above line as-is. This means including jdbc:mysql:// - this is important!

levels:
  2: 1000
  3: 2000
  4: 3000
  5: 4000
  6: 5000
  7: 6000
  8: 7000
  9: 8000